### ISSUE TITLE
Handle spawn and exit events from tracer

### ISSUE THREAD

**Issue by arkgil** [erlanglab/epl_st#1]
Handle exit and spawn events properly - delete or add nodes on the front-end.

**Comment by arkgil** [comment]
@michalslaski To achieve that I need to know how to delete nodes using VE. Do you know how to do that?

**Comment by michalslaski** [comment]
@arkgil as you decided to use 2D visualization for your new view instead, I guess the question is not urgent at the moment, right? I will try to get back to you on this one, once we start working on a view requiring 3D.

**Comment by arkgil** [comment]
Yes, I believe it is no longer valid issue. I'll close it for now.
