### ISSUE TITLE
Use 2D rendering library

### ISSUE THREAD

**Issue by arkgil** [erlanglab/epl_st#4]
Current candidates are:
* [SigmaJS](http://sigmajs.org/)
* [VivaGraphJS](https://github.com/anvaka/VivaGraphJS)

**Comment by arkgil** [comment]
UI will be included in erlanglab/erlangpl-ui repository, so we just need to delete static files from this repository.

**Comment by michalslaski** [comment]
Deleted static files in https://github.com/erlanglab/epl_st/commit/7f99a3cf06c2c18faf275a138c384efd826bbe4a
