### ISSUE TITLE
rebar expects repo name to be the same as app name

### ISSUE THREAD

**Issue by michalslaski** [erlanglab/epl_st#6]
src/epl_st.app.src declares name of the application to be epl_st, but the repo name is different (epl_sup_tree) and it confuses rebar. Let's stick to one name of this plugin.

**Comment by arkgil** [comment]
Alright, I'd go with `epl_st`.

**Comment by michalslaski** [comment]
Fixed in https://github.com/erlanglab/epl_st/commit/233095b0ec4a15b3ea1fa2b457f8304c9945cb18 and https://github.com/erlanglab/epl_st/commit/b7e3bf42a48ee5dafbe1b9b2eb950d78a24a0077
