### ISSUE TITLE
Handle `undefined` atom as a valid child returned by `supervisor:which_children`

### ISSUE THREAD

**Issue by arkgil** [erlanglab/epl_st#7]
In the [docs](http://www1.erlang.org/doc/man/supervisor.html#which_children-1) it's clearly stated that the second element of child spec tuple returned by `supervisor:which_children` may return an atom `undefined`.

The bug causes a crash of `epl_st` application (see erlanglab/erlangpl#43) and should be fixed as soon as possible.

I believe this is a good starter level issue, so if anyone's interested in contributing, please do! ❤️ 

[Here](https://github.com/erlanglab/epl_st/blob/master/src/epl_st.erl#L95) is a function which causes the crash, `undefined` atom should be handled as separate function clause.

**Comment by entone** [comment]
Don't have time to dig into it, but this is causing crashes for me as well.

**Comment by arkgil** [comment]
Closed without explanation, sorry. It is now fixed on this application's side, now we need to update `erlangpl` to include a new version, and everything should work as expected 👍

**Comment by arkgil** [comment]
@entone the issue is now fixed with `erlangpl` 0.6.1. Please pull from master branch or download new version of prebuilt script ([link](https://github.com/erlanglab/erlangpl/releases/download/0.6.1/erlangpl.tar.gz)). Cheers! 🙂

**Comment by entone** [comment]
Fixed here as well, thanks!
